//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vacation.Models
{
	using System;
	using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public partial class DetailOrder
	{
		public int Id { get; set; }
		public int Order_Id { get; set; }
		public string Tour_Name { get; set; }
		public int Tour_Qty { get; set; }
		[DataType(DataType.Currency), DisplayFormat(DataFormatString = "{0:0.0}")]
		public decimal Tour_Price { get; set; }

		public virtual Order Order { get; set; }
	}
}
